config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'photos#index'

  resources :photos
end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  has_one_attached :image
  has_many_attached :images


  has_one_attached :attachment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = current_user.photos.new(photo_params)

    if @photo.save
      redirect_to @photo
    else
      render :new
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])

    if @photo.destroy
      redirect_to root_url
    else
      redirect_to @photo
    end
  end

  private
    def photo_params
      params.require(:photo).permit(:caption, :user_id, :image, :attachment, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>InstagramJuly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body class="container pt-5">

    <% if notice %>
      <div class="alert alert-info alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <%= yield %>

    <footer class="footer text-muted pt-5">
      <ul class="list-unstyled list-inline">
        <li class="list-inline-item"><%= link_to 'Home', root_url %></li>
        <% if current_user %>
          <li class="list-inline-item"><%= link_to 'New Photo', new_photo_path %></li>
          <li class="list-inline-item"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="list-inline-item"><%= link_to 'Login', new_user_session_path %></li>
          <li class="list-inline item"><%= link_to 'Register', new_user_registration_path %></li>
        <% end %>
      </ul>

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </footer>
  </body>
</html>

app/views/photos/index.html.erb
<% if @photos.any? %>
  <section class="row">
    <% @photos.in_groups_of(3) do |group| %>
      <% group.compact.each do |photo|%>
        <section class="col-md-4">
          <section class="card mb-3">
            <%= link_to photo_url(photo) do %>
            <% if photo.image.attached? %>
              <%= image_tag photo.image, class: 'img-fluid' %>
            <% end %>
            <% end %>
            <section class="card-body">
              <p class="text-muted mb-0"><%= photo.user.email %></p>
              <p><%=  photo.caption %></p>
              <%= link_to photo_url(photo), method: :delete, class: 'text-danger' do %>
                <%= fa_icon "trash" %>
              <% end %>
            </section>
          </section>
        </section>
      <% end %>
    <% end %>
  </section>
<% end %>

app/views/photos/new.html.erb
<section class="row border pt-5 pb-5">
  <section class="col-md-6 offset-md-3">
    <h1>New Photo</h1>

    <%= form_for @photo do |form| %>
      <section class="form-group">
        <%= form.label :caption %><br>
        <%= form.text_area :caption, class: "form-control" %>
      </section>

      <section class="form-group">
        <%= form.label :image %><br>
        <%= form.file_field :image, class: "form-control-file" %>
      </section>

      <section class="form-group">
        <%= form.label :images %><br>
        <%= form.file_field :images, multiple: true, class: "form-control-file" %>
      </section>

      <section class="form-group">
        <%= form.label :attachment %><br>
        <%= form.file_field :attachment, class: "form-control-file" %>
      </section>


      <section class="form-group">
        <%= form.submit 'Upload', class: "btn btn-outline-primary" %>
      </section>
    <% end %>

  </section>
</section>

app/views/photos/show.html.erb
<section class="row">
  <section class="col-md-12">
    <h1><%= @photo.caption %></h1>

    <% if @photo.image.attached? %>
      <%= image_tag @photo.image, class: "img-fluid" %>
    <% end %>

    <% if @photo.images.attached? %>
      <% @photo.images.each do |image| %>
        <%= image_tag image, class: "img-fluid" %>
      <% end %>
    <% end %>

    <% if @photo.attachment.attached? %>
      <p>Attached</p>
      <%= link_to "Download", url_for(@photo.attachment) %>
    <% end %>
  </section>
</section>